### ISSUE TITLE
WebSocketServerHandler 中 使用hashMap 作为channelGroupMap在并发的情况下应该会有问题

### ISSUE THREAD

**Issue by zengbotang** [zhoumengkang/netty-websocket#1]
private static Map<Integer, ChannelGroup> channelGroupMap = new HashMap<Integer, ChannelGroup>();

上面这一行改为下面的会不会更好：
private static Map<Integer, ChannelGroup> channelGroupMap = new ConcurrentHashMap<Integer, ChannelGroup>();

**Comment by zhoumengkang** [comment]
说的对
