### ISSUE TITLE
不要来个书籍推荐吗?

### ISSUE THREAD

**Issue by EggsBlue** [zhoumengkang/netty-websocket#3]
代码应该是参考的<<Netty权威指南>>这本书吧,不要来个书籍推荐吗?

**Comment by zhoumengkang** [comment]
> 代码应该是参考的<<Netty权威指南>>这本书吧,不要来个书籍推荐吗?

没有看过呢，就是参考的netty github 官方的demo

**Comment by EggsBlue** [comment]
哦
